name: bda_busqueda_distribuida
services:
  db-metadata:
    container_name: db-metadata
    image: mysql:9
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./databases/volumes/mysql:/var/lib/mysql
      - ./secrets/mysql:/run/secrets
    networks:
      default_network:
        ipv4_address: 172.18.0.2

  db-content:
    container_name: db-content
    image: mongo:8.2-noble
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./databases/volumes/mongo:/data/db
      - ./secrets/mongo:/run/secrets
    networks:
      default_network:
        ipv4_address: 172.18.0.3

  db-index:
    container_name: db-index
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./databases/volumes/postgres:/var/lib/postgresql/data
      - ./secrets/postgres:/run/secrets
    networks:
      default_network:
        ipv4_address: 172.18.0.4

  broker:
    container_name: broker
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
    depends_on:
      - db-metadata
      - db-content
      - db-index
    networks:
      default_network:
        ipv4_address: 172.18.0.5

  crawler:
    container_name: crawler
    build:
      context: ./crawler
    image: crawler:latest
    restart: unless-stopped
    volumes:
      - ./rabbitmq/crawler.ini:/usr/src/app/config/crawler.ini
    depends_on:
      - db-metadata
      - db-content
      - db-index
      - broker
    networks:
      default_network:
        ipv4_address: 172.18.0.6

  # consumer:
  #   container_name: consumer
  #   build:
  #     context: ./consumer
  #   image: consumer:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./rabbitmq/consumer.ini:/usr/src/app/config/consumer.ini
  #   depends_on:
  #     - db-metadata
  #     - db-content
  #     - db-index
  #     - broker
  #     - crawler

networks:
  default_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16