name: bda_busqueda_distribuida
services:
  db-metadata:
    container_name: db-metadata
    image: mysql:9
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./databases/volumes/mysql:/var/lib/mysql
      - ./databases/init/mysql:/docker-entrypoint-initdb.d
      - ./secrets/mysql:/run/secrets

  db-content:
    container_name: db-content
    image: mongo:8.2-noble
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./databases/volumes/mongo:/data/db
      - ./databases/init/mongo:/docker-entrypoint-initdb.d
      - ./secrets/mongo:/run/secrets

  db-index:
    container_name: db-index
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./databases/volumes/postgres:/var/lib/postgresql/data
      - ./databases/init/postgres:/docker-entrypoint-initdb.d
      - ./secrets/postgres:/run/secrets

  broker:
    container_name: broker
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
    depends_on:
      - db-metadata
      - db-content
      - db-index

  crawler:
    container_name: crawler
    build:
      context: ./crawler
    image: crawler:latest
    restart: unless-stopped
    volumes:
      - ./rabbitmq/crawler.ini:/usr/src/app/config/crawler.ini
    depends_on:
      - db-metadata
      - db-content
      - db-index
      - broker

  # Backend. Just added.
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db-metadata
      - db-content
      - db-index
      - broker
    networks:
      - distributed_network

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    image: consumer:latest
    restart: unless-stopped
    volumes:
      - ./rabbitmq/consumer.ini:/usr/src/app/config/consumer.ini
    depends_on:
      - db-metadata
      - db-content
      - db-index
      - broker
      - crawler

networks:
  distributed_network:
    driver: bridge
