name: bda_busqueda_distribuida
services:
  db-metadata:
    container_name: db_metadata
    image: mysql:9
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql:/var/lib/mysql
      - ./secrets/mysql:/run/secrets

  db-content:
    container_name: db-content
    image: mongo:8.2-noble
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./databases/mongo:/data/db
      - ./secrets/mongo:/run/secrets

  db-index:
    container_name: db-index
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
      - ./secrets/postgres:/run/secrets

  broker:
    container_name: broker
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
    depends_on:
      - db-metadata
      - db-content
      - db-index

  crawler:
    container_name: crawler
    build:
      context: ./crawler
    restart: unless-stopped
    depends_on:
      - db-metadata
      - db-content
      - db-index
      - broker